trial_config:
  keypress_fj_response: false
  reward_duration_msec: null
  incorrect_duration_msec: null
  correct_feedback_lockout_duration_msec: 500
  incorrect_feedback_lockout_duration_msec: 1500
  show_fixation: false
  show_feedback: true
  stimulus_duration_msec: 0
  calibration_stimulus_duration_msec: 0
  post_stimulus_delay_duration_msec: 0
  keep_stimulus_on: true
  stimulus_width_degrees: 16
  choice_width_degrees_default: 4
  choice_duration_msec: 20000 # 20 seconds
  pre_choice_lockout_delay_duration_msec: 200
  intertrial_delay_duration_msec: 200

  # fallback choice_names --> vals in trialsets.csv will override these
  choice_names_order: ["tongue","feet"]
  choice_names_aliases:
    tongue: "Tongue"
    feet: "Feet"
  choice_aliases_random_shuffle: false
  choice_url_suffix: "_text_icon.png"
  query_string: "Which category matches the image?"
  feedback_correct_url: "https://miljspsych.s3.amazonaws.com/resources/assets/images/feedback_is_correct_image.png"
  feedback_incorrect_url: "https://miljspsych.s3.amazonaws.com/resources/assets/images/feedback_is_incorrect_image.png"
  choice_image_bucket_name: "maggie-experiment"
  shuffle_choice_order: false
  rotate_choice_order: false

hit_config:
  title: "Classify tongue vs. feet motor imagery signal images"
  description: "One block: tongue-vs-feet. Learn by trial and error."
  reward: 0.20
  num_respondents: 10
  max_time_seconds: 300 # 1800 = 30 minutes, 3600 = 1 hour
  lifetime_seconds: 259200 # 259200 = 3 days, 86400 = 1 day
  frame_height: 0 # The height of the task frame (if zero, resizes automatically)
  autoapprove: true